#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x polybar > /dev/null || ~/.config/polybar/launch.sh --hack &
pgrep -x fcitx5 > /dev/null || fcitx5 &
feh --bg-fill ~/Pictures/wallpaper/d9034a90f603738d0d98cf04be1bb051f919eccd.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        10
bspc config focused_border_color '#BF616A'
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true


bspc rule -a Microsoft-edge desktop='^2' follow=on focus=on
bspc rule -a weixin desktop='^9' state=floating follow=on focus=on
bspc rule -a qqmusic desktop='^9' state=floating
bspc rule -a Steam desktop='^8' state=floating
bspc rule -a Thunar  state=floating
bspc rule -a Code desktop='^3' follow=on

bspc rule -a Bochs state=floating
bspc rule -a Fsearch state=floating
